export * from './types';
export * from './price-oracle';
export * from './sources/chainlink';
export * from './sources/dexscreener';
export * from './sources/pyth';
export * from './sources/helius';
import { PluginManager } from '@lumix/core';
import { PriceOraclePlugin } from './price-oracle';
import { PriceOracleConfig } from './types';
export declare function createPriceOraclePlugin(config?: PriceOracleConfig): PriceOraclePlugin;
export declare function initializePriceOraclePlugin(manager: PluginManager, config?: PriceOracleConfig): Promise<PriceOraclePlugin>;
